blank_issues_enabled: false
contact_links:
  - name: Official poste.io Issue Tracker
    url: https://bitbucket.org/analogic/mailserver/issues/
    about: Go here if you didn't install poste from this repo
